from system.core.router import routes

routes['default_controller'] = 'home'
routes['/login']='home#login'
routes['/register']='home#register'
routes['/dashboard']='home#dashboard'
routes['POST']['/adduser']='Users#adduser'
routes['POST']['/loginuser']='Users#loginuser'
routes['/logout']='Users#logout'
routes['/']='home#index'
routes['/users/show/<user_id>'] = 'home#userpage'
routes['/users/new'] = 'home#adminadd'
routes['/users/edit/<user_id>'] = 'home#edit'
routes['/users/remove/<user_id>'] = 'home#remove'
routes['POST']['/updateinfo/<user_id>'] = 'Users#updateinfo'
