from system.core.router import routes

routes['default_controller'] = 'home'
routes['/login']='home#login'
routes['/register']='home#register'
routes['/dashboard']='home#dashboard'
routes['POST']['/adduser']='Users#adduser'
routes['POST']['/loginuser']='Users#loginuser'
routes['/logout']='Users#logout'
routes['/']='home#index'
routes['/users/show/<user_id>'] = 'home#userpage'
routes['/users/new'] = 'home#adminadd'
routes['/users/edit/<user_id>'] = 'home#edit'
routes['/users/remove/<user_id>'] = 'home#remove'
routes['POST']['/users/updateinfo/<user_id>'] = 'Users#updateinfo'
routes['/users/remove/<user_id>'] = 'Users#destroy'
routes['POST']['/messages/addmessage/<user_id>'] = 'Messages#addmsg'
routes['POST']['/messages/addcomment/<user_id>/<message_id>'] = 'Messages#addcmt'
